version: 2
jobs:
  build:
    working_directory: /smart-dom
    steps:
      - run:
          name: Install dependencies
          command: yarn install
      - run: 
          name: Run tests
          command:  yarn run validate
